// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYEXsAXb272HjgyLOhMYHcSNAmwAcuNY',
    appId: '1:185072342007:web:092250702176a70a4cd4f2',
    messagingSenderId: '185072342007',
    projectId: 'startwise-2a0bb',
    authDomain: 'startwise-2a0bb.firebaseapp.com',
    storageBucket: 'startwise-2a0bb.firebasestorage.app',
    measurementId: 'G-ZMKFHCVC1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgqwmR3mZdtTDhdyN8lFWHPDJQZJwX1s',
    appId: '1:185072342007:android:32937716d739622e4cd4f2',
    messagingSenderId: '185072342007',
    projectId: 'startwise-2a0bb',
    storageBucket: 'startwise-2a0bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRMem7P7QtpfaDp7cJIOd3xladx661h-o',
    appId: '1:185072342007:ios:2858571dd032d98f4cd4f2',
    messagingSenderId: '185072342007',
    projectId: 'startwise-2a0bb',
    storageBucket: 'startwise-2a0bb.firebasestorage.app',
    iosBundleId: 'com.example.solutionChanllenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRMem7P7QtpfaDp7cJIOd3xladx661h-o',
    appId: '1:185072342007:ios:2858571dd032d98f4cd4f2',
    messagingSenderId: '185072342007',
    projectId: 'startwise-2a0bb',
    storageBucket: 'startwise-2a0bb.firebasestorage.app',
    iosBundleId: 'com.example.solutionChanllenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXYEXsAXb272HjgyLOhMYHcSNAmwAcuNY',
    appId: '1:185072342007:web:bd1d4c1d8ea20dba4cd4f2',
    messagingSenderId: '185072342007',
    projectId: 'startwise-2a0bb',
    authDomain: 'startwise-2a0bb.firebaseapp.com',
    storageBucket: 'startwise-2a0bb.firebasestorage.app',
    measurementId: 'G-CLGMV4FK09',
  );
}
